
### 웹툰 장르별 목록 조회
GET http://43.200.18.88:8080/api/v1/webtoons?genre=FANTASY
Content-Type: application/json; charset=UTF-8



### 웹툰 등록
POST http://43.200.18.88:8080/api/v1/webtoons
Content-Type: application/json; charset=UTF-8

{
	"title": "웹툰 제목",
	"thumbnail": "URL",
	"prologue": "URL",
	"story": "스토리 설명",
	"description": "한줄 요약",
	"genre": "판타지",	
}