import type { Metadata } from 'next';
import '../../globals.css';

import Footer from '@/app/_component/Footer';
import '@mdi/font/css/materialdesignicons.min.css';
import RQProvider from '@/app/_component/RQProvider';
import Header from './_component/Header';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Dreamketcher',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={`antialiased flex flex-col min-h-screen`}>
        <RQProvider>
          <Header />
          <div className="flex w-full justify-center">
            <div className="bg-white text-black max-w-[1200px] w-full">
              <Suspense>{children}</Suspense>
            </div>
          </div>
          <Footer />
        </RQProvider>
      </body>
    </html>
  );
}
