import type { Metadata } from 'next';
import '../globals.css';
import BackofficeHeader from './_component/BackofficeHeader';
import { Suspense } from 'react';

import RQProvider from '../_component/RQProvider';

export const metadata: Metadata = {
  title: 'Dreamketcher',
  description: 'Generated by create next app',
};

export default function BackofficeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen w-full bg-white text-black">
      <RQProvider>
        <BackofficeHeader />
        <div className="flex-1">{children}</div>
      </RQProvider>
    </div>
  );
}
