import type { Metadata } from 'next';
import '../globals.css';
import Header from '@/app/_component/Header';
import Footer from '@/app/_component/Footer';
import { Suspense } from 'react';

import RQProvider from '../_component/RQProvider';

export const metadata: Metadata = {
  title: 'Dreamketcher',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="antialiased flex flex-col min-h-screen bg-white overflow-x-hidden">
      <RQProvider>
        <Suspense>
          <Header></Header>
          {children}
          <Footer></Footer>
        </Suspense>
      </RQProvider>
    </div>
  );
}
